import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-screen h-screen justify-center items-center bg-slate-50">
        <main className="flex flex-col w-full h-full bg-white space-y-8 lg:w-96 lg:h-2/5 lg:rounded-lg lg:shadow-lg px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
